### ISSUE TITLE
undefined method `resolved_build_setting' for nil:NilClass

### ISSUE THREAD

**Issue by dlargen33** [SiarheiFedartsou/fastlane-plugin-versioning#50]
When trying to execute the action   increment_build_number_in_plist(target: "name") it is failing with   undefined method `resolved_build_setting' for nil:NilClass

I  am new to fastlane so let me know what you need to help debug this.

**Comment by jdouglas-nz** [comment]
hey @dlargen33,
my first thought would be to confirm whether the script you're running has the right context.
By context I mean, that you are either `cd`'ed into the directory with the `.plist` or that you pass a valid path to one.

**Comment by slorber** [comment]
Hi,

Had the problem, and figured out that it's not a problem of xcodeprof location (it emits a different error message).

In my case it was due to using a bad target name. 
For some reasons we updated our app and added a capital letter to the target, leading to this fastlane script failing.

Having a better error message in case of bad target would be helpful, had to look at ruby source code to understand what might be the cause :)
