### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by ansf** [SiarheiFedartsou/fastlane-plugin-versioning#68]
Could you please provide a changelog or annotate the releases accordingly? It would be nice to know what changed when updating this plugin.

Thanks!

**Comment by jdouglas-nz** [comment]
hey @ansf, thanks for creating an issue.
I just found that github makes it really easy to do based on tags - and will generate release notes for me. pretty nifty. 
I'll start with that if you don't mind 😅 
Hopefully you find what you're looking for in it - otherwise please feel free to comment on this issue again

**Comment by ansf** [comment]
that's awesome. thank you so much :)
